[program:backend-scheduler]
command=/home/ubuntu/fastapi-async-sqlmodel-boilerplate/deploy/native/scripts/backend-scheduler
user=ubuntu
autostart=true
autorestart=true
redirect_stderr=true
stderr_logfile=/home/ubuntu/fastapi-async-sqlmodel-boilerplate/deploy/native/logs/scheduler-error.log
stdout_logfile=/home/ubuntu/fastapi-async-sqlmodel-boilerplate/deploy/native/logs/scheduler-output.log
