"""empty message

Revision ID: e7417594926f
Revises: 
Create Date: 2026-06-08 20:28:49.987127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e7417594926f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create sequences first
    op.execute("CREATE SEQUENCE IF NOT EXISTS taskset_id_sequence START 1")
    op.execute("CREATE SEQUENCE IF NOT EXISTS task_id_sequence START 1")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_task_meta',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('task_id_sequence')"), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=155), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('result', sa.PickleType(), nullable=True),
    sa.Column('date_done', sa.DateTime(), nullable=True),
    sa.Column('traceback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=155), nullable=True),
    sa.Column('args', sa.LargeBinary(), nullable=True),
    sa.Column('kwargs', sa.LargeBinary(), nullable=True),
    sa.Column('worker', sqlmodel.sql.sqltypes.AutoString(length=155), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('queue', sqlmodel.sql.sqltypes.AutoString(length=155), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id'),
    comment='Celery Task result/status'
    )
    op.create_table('sys_taskset_meta',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('taskset_id_sequence')"), nullable=False),
    sa.Column('taskset_id', sqlmodel.sql.sqltypes.AutoString(length=155), nullable=False),
    sa.Column('result', sa.PickleType(), nullable=True),
    sa.Column('date_done', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taskset_id'),
    comment='Celery TaskSet result'
    )
    op.create_table('sys_tier',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Tier information'
    )
    op.create_index(op.f('ix_sys_tier_id'), 'sys_tier', ['id'], unique=False)
    op.create_table('sys_token_blacklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Token blacklist for authentication'
    )
    op.create_index(op.f('ix_sys_token_blacklist_id'), 'sys_token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_sys_token_blacklist_token'), 'sys_token_blacklist', ['token'], unique=False)
    op.create_table('sys_rate_limit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tier_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['sys_tier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Rate limit configuration'
    )
    op.create_index(op.f('ix_sys_rate_limit_id'), 'sys_rate_limit', ['id'], unique=False)
    op.create_index(op.f('ix_sys_rate_limit_tier_id'), 'sys_rate_limit', ['tier_id'], unique=False)
    op.create_table('sys_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('profile_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tier_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['sys_tier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='User account information'
    )
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=True)
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_is_deleted'), 'sys_user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_user_tier_id'), 'sys_user', ['tier_id'], unique=False)
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.create_table('blog_post',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=63206), nullable=False),
    sa.Column('media_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Blog post information'
    )
    op.create_index(op.f('ix_blog_post_id'), 'blog_post', ['id'], unique=False)
    op.create_index(op.f('ix_blog_post_is_deleted'), 'blog_post', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_blog_post_user_id'), 'blog_post', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_post_user_id'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_is_deleted'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_id'), table_name='blog_post')
    op.drop_table('blog_post')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_tier_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_is_deleted'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_rate_limit_tier_id'), table_name='sys_rate_limit')
    op.drop_index(op.f('ix_sys_rate_limit_id'), table_name='sys_rate_limit')
    op.drop_table('sys_rate_limit')
    op.drop_index(op.f('ix_sys_token_blacklist_token'), table_name='sys_token_blacklist')
    op.drop_index(op.f('ix_sys_token_blacklist_id'), table_name='sys_token_blacklist')
    op.drop_table('sys_token_blacklist')
    op.drop_index(op.f('ix_sys_tier_id'), table_name='sys_tier')
    op.drop_table('sys_tier')
    op.drop_table('sys_taskset_meta')
    op.drop_table('sys_task_meta')
    # ### end Alembic commands ###

    op.execute("DROP SEQUENCE IF EXISTS task_id_sequence")
    op.execute("DROP SEQUENCE IF EXISTS taskset_id_sequence")
