[program:backend-api]
command=/home/ubuntu/fastapi-async-sqlmodel-boilerplate/deploy/supervisor/backend-api
user=ubuntu
autostart=true
autorestart=true
redirect_stderr=true
stderr_logfile=/home/ubuntu/fastapi-async-sqlmodel-boilerplate/deploy/logs/api-error.log
stdout_logfile=/home/ubuntu/fastapi-async-sqlmodel-boilerplate/deploy/logs/api-output.log